# Generated by Django 5.1.5 on 2025-07-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_marks', models.IntegerField()),
                ('max_marks', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
            ],
        ),
    ]
