# Generated by Django 5.1.5 on 2025-07-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt_panel', '0002_gradescale'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
